### ISSUE TITLE
Method Error when trying to run example code

### ISSUE THREAD

**Issue by nolsman** [SciML/StructuralIdentifiability.jl#107]
I was just trying to run the example code copied directly from here: https://github.com/SciML/StructuralIdentifiability.jl/blob/master/examples/CRN.jl

and am getting the output pasted below. I also tried running the library on an ODE model of my own and other examples, always getting the same output. Is this a known bug? I tried running `Pkg.update("StructuralIndentifiability") to see if that helped, but no luck.

`Singular.jl, based on
                     SINGULAR                               /
 A Computer Algebra System for Polynomial Computations     /  Singular.jl: 0.5.7
                                                         0<   Singular   : 4.2.0p1
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann   \
FB Mathematik der Universitaet, D-67653 Kaiserslautern      \
     
┌ Info: Summary of the model:
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/ODE.jl:299
┌ Info: State variables: x2, x5, x6, x3, x4, x1
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/ODE.jl:300
┌ Info: Parameters: k5, k3, k4, k2, k6, k1
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/ODE.jl:301
┌ Info: Inputs: 
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/ODE.jl:302
┌ Info: Outputs: y1, y2
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/ODE.jl:303
┌ Info: Assessing local identifiability
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/StructuralIdentifiability.jl:92
┌ Info: Local identifiability assessed in 4.943092853 seconds
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/StructuralIdentifiability.jl:94
┌ Info: Assessing global identifiability
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/StructuralIdentifiability.jl:109
┌ Info: Computing IO-equations
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/global_identifiability.jl:200
┌ Info: Computed in 8.872011279 seconds
│   :ioeq_time = ioeq_time
│   ioeq_time = 8.872011279
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/global_identifiability.jl:203
┌ Info: Computing Wronskians
└ @ StructuralIdentifiability /home/nao5/.julia/packages/StructuralIdentifiability/wOUIO/src/global_identifiability.jl:206
MethodError: Cannot `convert` an object of type 
  Nemo.gfp_abs_series to an object of type 
  AbstractAlgebra.Generic.AbsSeries
Closest candidates are:
  convert(::Type{T1}, ::CxxWrap.CxxWrapCore.SmartPointer{DerivedT}) where {BaseT, T1<:BaseT, DerivedT<:BaseT} at /home/nao5/.julia/packages/CxxWrap/OcN1Z/src/CxxWrap.jl:276
  convert(::Type{T}, ::T) where T at essentials.jl:205

Stacktrace:
  [1] setindex!(h::Dict{AbstractAlgebra.MPolyElem, AbstractAlgebra.Generic.AbsSeries}, v0::Nemo.gfp_abs_series, key::Nemo.gfp_mpoly)
    @ Base ./dict.jl:382
  [2] wronskian(io_equations::Dict{Nemo.fmpq_mpoly, Nemo.fmpq_mpoly}, ode::ODE{Nemo.fmpq_mpoly})
    @ StructuralIdentifiability ~/.julia/packages/StructuralIdentifiability/wOUIO/src/wronskian.jl:223
  [3] macro expansion
    @ ./timing.jl:287 [inlined]
  [4] assess_global_identifiability(ode::ODE{Nemo.fmpq_mpoly}, funcs_to_check::Vector{Any}, p::Float64; var_change::Symbol, gb_method::Symbol)
    @ StructuralIdentifiability ~/.julia/packages/StructuralIdentifiability/wOUIO/src/global_identifiability.jl:207
  [5] assess_global_identifiability
    @ ~/.julia/packages/StructuralIdentifiability/wOUIO/src/global_identifiability.jl:200 [inlined]
  [6] macro expansion
    @ ./timing.jl:287 [inlined]
  [7] assess_identifiability(ode::ODE{Nemo.fmpq_mpoly}, funcs_to_check::Vector{Nemo.fmpq_mpoly}, p::Float64)
    @ StructuralIdentifiability ~/.julia/packages/StructuralIdentifiability/wOUIO/src/StructuralIdentifiability.jl:110
  [8] assess_identifiability (repeats 2 times)
    @ ~/.julia/packages/StructuralIdentifiability/wOUIO/src/StructuralIdentifiability.jl:68 [inlined]
  [9] top-level scope
    @ ./timing.jl:210 [inlined]
 [10] top-level scope
    @ ./In[1]:0
 [11] eval
    @ ./boot.jl:360 [inlined]
 [12] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1116`

**Comment by pogudingleb** [comment]
@nolsman Could you give your `st -m` (versions of the packages)?

**Comment by nolsman** [comment]
Sure, this is what I get out:

Pkg.status("StructuralIdentifiability")
Status `~/.julia/environments/v1.6/Project.toml`
[220ca800] StructuralIdentifiability v0.1.0

**Comment by pogudingleb** [comment]
It looks like you have a very old version of the package, could you try to install the up-to-date one with `add StructuralIdentifiability@0.3.10`?

**Comment by nolsman** [comment]
Yup that fixed it! No idea why Pkg defaulted to installing the v0.1.0, but it all seems good now. Thanks for the help!
