### ISSUE TITLE
system class

### ISSUE THREAD

**Issue by FabiJa** [SciML/StructuralIdentifiability.jl#126]
Hi,

I am just curious and testing your library. 

Now I have one question: 
Which type of system does your library support? Only polynomial ODEs?
I am asking because I am getting the following error, when parsing a MWE model:
` ode = @ODEmodel(
    x1'(t) = a*x1(t)+sin(u(t)),
    y(t) = x1(t) 
    )`
This leads to the following error:
`[ Info: Summary of the model:
[ Info: State variables: x1
[ Info: Parameters: a, sin
[ Info: Inputs: u
[ Info: Outputs: y
ERROR: Number of variables does not match number o
f values`
where `sin` is recognized as parameter. Am I doing something wrong or is this a limitation of your toolbox?
Thx.

**Comment by iliailmer** [comment]
Hi @FabiJa , thank you for your question! Yes, currently only rational functions are supported for the right-hand side of the ODE system.

**Comment by FabiJa** [comment]
Ok, thank you. I missed this in the documentation.
