### ISSUE TITLE
Function exp is not supported

### ISSUE THREAD

**Issue by kikiggg** [SciML/StructuralIdentifiability.jl#139]
Hi 

I want to check StructuralIdentifiability some differential equation which include "exp"  but it didnt work   with message "Function exp is not supported"

Is there any solutiong for that? or internally not supported?

Thank you 
Park

**Comment by iliailmer** [comment]
Hi @kikiggg , StructuralIdentifiability.jl supports ODE models with rational (polynomial) functions. You can try to modify your ODE so that `exp` is "implicit", for example

```
# original:
x' = A * exp(B * t) * x

# modified
x' = A * g * x
g' = B * g
```

**Comment by ChrisRackauckas** [comment]
We could make that a ModelingToolkit pass of sorts, worth an issue.

**Comment by pogudingleb** [comment]
Small addition to the comment of @iliailmer 
It is better to set `g = A * exp(B * t)`, this way the resulting system will be
```
x' = g * x
g' = B * g
```
So the number degrees of freedom (num of states plus num of parameters will be the same), so the identifiability results can be transferred between the original system and the new one.

@ChrisRackauckas  Here is a subtlety: one should ideally try to make the transformation carefully, keeping the dimension of the problem. Not impossible, definitely worth an issue, I will create one.

**Comment by pogudingleb** [comment]
I created a [separate issue](https://github.com/SciML/StructuralIdentifiability.jl/issues/144) for handling non-rational models containing my thoughts on the matter. It subsumes the present issue, so I close it.
