### ISSUE TITLE
ode for input

### ISSUE THREAD

**Issue by jigiisc** [SciML/StructuralIdentifiability.jl#143]
Hi, 

I have an ode for the input in my model. See below as an example. Is there any way to define u(t) as an input in such a case? Thanks.

ode = @ODEmodel(
    x1'(t) = -(a01 + a21) * x1(t) + a12 * x2(t) + u(t),
    x2'(t) = a21 * x1(t) - a12 * x2(t) - x3(t) / b,
    x3'(t) = x3(t),
    u'(t) = -kd*u(t),
    y(t) = x2(t)
)

**Comment by pogudingleb** [comment]
So I guess that you would like to reflect the fact that it is known, right? Then you can just add an output for it `y2(t) = u(t)`.
Does this sound like what you had in mind?

**Comment by jigiisc** [comment]
Thanks for your reply!
The input is known but it is not an observable. In my model the input is a drug that binds to other species and also gets degraded.   For example, see the following two equations, the drug binds to the receptor R and forms a complex RL. These are just two equations out of 23 odes from my model. I want to assess the identifiability provided that the drug is an input. 

R'(t) = - kasRL*drug(t)*R(t) + kdisRL*RL(t),
drug'(t) =  - kasRL*drug(t)*R(t) + kdisRL*RL(t) - kd_drug*drug(t),

**Comment by pogudingleb** [comment]
Thank you for clarifying ! I am bit confused by possible meaning of `know but now observable`. From what you describe it sounds to me that there is a known input flow of the drug (which is an input not satisfying any equations) and there is the total concentration of the drug in the organ which influenced by this input flow but also by other species (as you describe). So wouldn't it make sense to have here one input and one state ?

**Comment by jigiisc** [comment]
Thanks. I think you may be right, I should include the input as an observable since it is known and have odes for that. Just few questions though, in the following example, including the input u(t) makes it fully identifiable, so how does the input affects identifiability? 
ode = @ODEmodel(
	x1'(t) = k * (1 - x1(t) - x2(t)) + u(t),
	x2'(t) = r * (1 - x1(t) - x2(t)),
	y(t) = x1(t)
)

Also, I understand that local meaning finite interval, so what interval specifically is used in the local method?

**Comment by pogudingleb** [comment]
> including the input u(t) makes it fully identifiable, so how does the input affects identifiability?

It allows you to perturb the trajectory and thus extract more information. Another way to put this is that this input breaks the symmetries of the model: without it you could apply any linear operator with (1, 1) being eigenvector to `(x1, x2)` and preserve the output (hence, nonidentifiability). With this input this does not work. 

> Also, I understand that local meaning finite interval, so what interval specifically is used in the local method?

Local here means that, for generic input-output data, there will be only finitely many possible parameter values. In other words, that parameter value is unique locally in small neighbourhood. Technically, the algorithm to check this relies on the [Hermann-Krener observability criterion](https://www.math.ucdavis.edu/~krener/1-25/10.IEEETAC77.pdf). The specific algorithm follows [the paper by Sedoglavic](https://www.sciencedirect.com/science/article/pii/S0747717102905328?via%3Dihub).

**Comment by jigiisc** [comment]
Thanks, that helps. I wanted to know if it is possible to get this finite interval for each parameter but looking at those papers I guess it might be difficult task.   

Also, fyi, I am facing similar issue as reported under "Stuck at "Computing IO-equations"" while using the global method.  I get "Problem in the Flint-Subsystem" after "[ Info: Computing IO-equations".

**Comment by pogudingleb** [comment]
@jigiisc 
Computing IO-equations is typically the bottleneck. If it is fine for you to share the model with me, I can look at it and maybe propose a workaround. (if you do not want to post it here, you can email it to gleb.pogudin@polytechnique.edu)
