### ISSUE TITLE
Write how to define models with MTK

### ISSUE THREAD

**Issue by pogudingleb** [SciML/StructuralIdentifiability.jl#155]
Current version of tutorials describe only one way of defining a model, using the `@ODEmodel` macro. A good text about using MTK for this (and maybe even in conjunction with Catalyst) would be great to have.

UPD: Thanks to @saumil-sh  - there is such a text in the MTK tutorials but it would be great to have this in the `StructuralIdentifiability.jl` docs as well

**Comment by saumil-sh** [comment]
I found this in [`ModelingToolkit.jl` tutorials](https://docs.sciml.ai/ModelingToolkit/stable/tutorials/parameter_identifiability/) :)

**Comment by pogudingleb** [comment]
@saumil-sh 
Thanks, I forgot about this tutorial ! Anyway, would be good to have something here as well.

**Comment by ven-k** [comment]
Note that now its being updated: https://github.com/SciML/ModelingToolkit.jl/blob/fa153f0791408a46eb788d90500e1acc688dfb80/docs/src/tutorials/parameter_identifiability.md
