### ISSUE TITLE
Structural Analysis for algebraic difference equations (DiscreteSystem)

### ISSUE THREAD

**Issue by RodrigoZepeda** [SciML/StructuralIdentifiability.jl#175]
Some biological models are represented via difference equations of the form: $x(t + 1) = f\big( x(t), \theta \big)$. According to Chris Rackauckas [on Twitter](https://twitter.com/ChrisRackauckas/status/1659549992296538112?s=20), an extension of the identifiability functions could be made for those systems using the `DiscreteSystem` from `ModelingToolkit`. 

Some references on the subject are:

Nõmm, Sven, and C. H. Moog. "[Identifiability of discrete-time nonlinear systems.](https://www.sciencedirect.com/science/article/pii/S1474667017312454)" IFAC Proceedings Volumes 37.13 (2004): 333-338.

Nõmm, Sven, and Claude H. Moog. "[Further results on identifiability of discrete-time nonlinear systems](https://www.sciencedirect.com/science/article/abs/pii/S0005109816300012)." Automatica 68 (2016): 69-74.

**Comment by pogudingleb** [comment]
@RodrigoZepeda 
Thanks for bringing this up! Indeed, at least for local identifiability this does not seem to be complicated. 
If you have some models you would like to check, let me know - I can try to prioritise this.

**Comment by RodrigoZepeda** [comment]
I'm working with State Space Models and variations upon the SIR model from epidemiology. I cannot copy the exact example. However, here are some similar toy models:

```
using ModelingToolkit, DifferentialEquations

#SIR Model (should not be identifiable)
@parameters α β
@variables t S(t) I(t) R(t)
D = Difference(t; dt=1.0)

eqs = [D(S) ~ S - β*S*I,
       D(I) ~ I + β*S*I - α*I,
       D(R) ~ R + α*I]       
@named sir = DiscreteSystem(eqs)

#Linear model (A can be a matrix)
#Identifiability depends upon the matrix
@parameters A , b
@variables t x(t)
D = Difference(t; dt=1.0)

eqs = [D(x) ~ A*x + b]       
@named linear = DiscreteSystem(eqs)

#An example that can be identified whenever x(0) != 0
@parameters θ
@variables t x(t)
D = Difference(t; dt=1.0)

eqs = [D(x) ~ θ*x^3]

@named eqs = DiscreteSystem(eqs)

#An example for local identifiability 
#(different values of θ for R^+ and R^-)
@parameters θ
@variables t x(t)
D = Difference(t; dt=1.0)

eqs = [D(x) ~ θ^2 + x]

@named eqs = DiscreteSystem(eqs)

#An example that cannot be identified 
@parameters θ β
@variables t x(t) y(t)
D = Difference(t; dt=1.0)

eqs = [D(x) ~ x + y,
       D(y) ~ θ + β]

@named eqs = DiscreteSystem(eqs)
```

I am happy to generate more toy models to test the algorithms and help any way I can within my limited expertise on the subject.

**Comment by pogudingleb** [comment]
@RodrigoZepeda 
Thanks for the examples !
I have implemented local identifiability check for discrete time systems, it is available in the current GitHub version (and can be installed by `Pkg.add("https://github.com/SciML/StructuralIdentifiability.jl")`).
Here is an example of computation:
```julia
using ModelingToolkit
using StructuralIdentifiability

@parameters α β
@variables t S(t) I(t) R(t) y(t)
D = Difference(t; dt = 1.0)

eqs = [D(S) ~ S - β * S * I, D(I) ~ I + β * S * I - α * I, D(R) ~ R + α * I]
@named sir = DiscreteSystem(eqs)

println(assess_local_identifiability(sir; measured_quantities = [y ~ I]))
```
which will print a dictionary from parameters and states to their identifiability (under assumption that the `I` compartment is observed).
Any feedback will be appreciated !

**Comment by RodrigoZepeda** [comment]
Woow. I'll take a look during the week for feedback and trying additional systems.

**Comment by pogudingleb** [comment]
Quick clarification: the algorithm check identifiability for generic initial conditions and exciting enough inputs, if the algorithm reports identifiability there may be still some singular solutions from which the parameters/states of interest cannot be identified.

**Comment by pogudingleb** [comment]
@RodrigoZepeda 
Thanks for testing!
The thing is that the outputs are expected to have new names, so the following will work fine
```julia
using ModelingToolkit, StructuralIdentifiability

@parameters α β
@variables t x(t) y1(t) y2(t)
D = Difference(t; dt=1.0)

eqs = [D(x) ~ α + (1/β)*x] #Doesn't work

@named eqs = DiscreteSystem(eqs)

assess_local_identifiability(eqs; measured_quantities = [y1 ~ x, y2 ~ β])
```
Let me know if this makes sense.

**Comment by RodrigoZepeda** [comment]
Ohhhhh ok this solves many of the weird isues I was having

**Comment by pogudingleb** [comment]
@RodrigoZepeda 
I thought about this issue and this is indeed not completely intuitive that one has to introduce extra names for the measured quantities. So I have added (to the current GitHub version) an option not to name these variables. The above example can be now also run as (the change in the last line)
```julia
using ModelingToolkit
using StructuralIdentifiability

@parameters α β
@variables t S(t) I(t) R(t) y(t)
D = Difference(t; dt = 1.0)

eqs = [D(S) ~ S - β * S * I, D(I) ~ I + β * S * I - α * I, D(R) ~ R + α * I]
@named sir = DiscreteSystem(eqs)

println(assess_local_identifiability(sir; measured_quantities = [I]))
```

**Comment by RodrigoZepeda** [comment]
Awesome! I'll try and add a tutorial on this to the documentation during the following week (June 20-something)

**Comment by pogudingleb** [comment]
@RodrigoZepeda 
I made a [simple tutorial](https://docs.sciml.ai/StructuralIdentifiability/dev/tutorials/discrete_time/) for this functionality, let me know what you think. If you have any interesting example(s) to add, it will be greatly appreciated

**Comment by RodrigoZepeda** [comment]
It looks great! Thank you. I'm out of the office for a while but will definitley come back here in ~ a month. Last time I completely forgot about my comment but feel free to ping me if I don't come back.

**Comment by pogudingleb** [comment]
> It looks great! Thank you. I'm out of the office for a while but will definitley come back here in ~ a month. Last time I completely forgot about my comment but feel free to ping me if I don't come back.

Thanks! Note that I have misinterpreted `Difference` from MTK in my first implementation, so make sure use use version `0.4.16` or older.
