### ISSUE TITLE
Need for a new release

### ISSUE THREAD

**Issue by ven-k** [SciML/StructuralIdentifiability.jl#216]
Can we have a new release of StructuralIdentifiability?

Groebner compat is bumped to 0.4; but that is unreleased[^1]. This results in following incompatibility while building MTK docs:

```juila
ERROR: Unsatisfiable requirements detected for package MultivariatePolynomials [102ac46a]:
 MultivariatePolynomials [102ac46a] log:
 ├─possible versions are: 0.2.0-0.5.2 or uninstalled
:
:
 └─restricted by compatibility requirements with Groebner [0b43b601] to versions: 0.4.3-0.4.7 — no versions left
   └─Groebner [0b43b601] log:
     ├─possible versions are: 0.1.0-0.4.4 or uninstalled
     ├─restricted by compatibility requirements with StructuralIdentifiability [220ca800] to versions: 0.2.0-0.3.6
     │ └─StructuralIdentifiability [220ca800] log:
     │   ├─possible versions are: 0.1.0-0.4.10 or uninstalled
     │   └─restricted to versions 0.4 by an explicit requirement, leaving only versions: 0.4.0-0.4.10
     └─restricted by compatibility requirements with Symbolics [0c5d862f] to versions: 0.3.0-0.4.4, leaving only versions: 0.3.0-0.3.6
       └─Symbolics [0c5d862f] log: see above
```

See full log here[^2]

[^1]:https://github.com/SciML/StructuralIdentifiability.jl/compare/v0.4.10...master#diff-72ed386c2a0cd1d23c0968297e70023ed98c22490d146dd89fc91f48369bad4dR32
[^2]:https://github.com/SciML/ModelingToolkit.jl/actions/runs/6406721277/job/17391912651?pr=2286#step:5:7

**Comment by pogudingleb** [comment]
Yes, we have to fix our documentation a bit, I hope we will make a release this week.

**Comment by YingboMa** [comment]
Could you at least do a patch release first? This is blocking MTK.

**Comment by sumiya11** [comment]
Made a patch release. Sorry for the inconvenience
