### ISSUE TITLE
Cannot find PreprocessODE function

### ISSUE THREAD

**Issue by TorkelE** [SciML/StructuralIdentifiability.jl#224]
I want to convert a ModelingToolkit ODE to the same ODE form as used in StructuralIdentifiabiltiy (and use it for various input). The function is documented, but does not seem to exist?

```julia
using StructuralIdentifiability
PreprocessODE
StructuralIdentifiability.PreprocessODE
```
Both the two bottom lines gives `UnderVarError`.

**Comment by pogudingleb** [comment]
Sorry, the documentation is now not in its best shape (next item on todo list), the function is now called `preprocess_ode`, [here](https://github.com/SciML/StructuralIdentifiability.jl/blob/master/src/ODE.jl#L516) is t.

**Comment by TorkelE** [comment]
Thanks :)

I am happy to close this, but if you want you can leave it open as a reminder about the documentation.

**Comment by pogudingleb** [comment]
Thanks :)
I think we have figure it out
