### ISSUE TITLE
Using `set_parameter_values` with ModelingToolkit type models

### ISSUE THREAD

**Issue by TorkelE** [SciML/StructuralIdentifiability.jl#225]
With Catalyst (and other packages) we generate models ranging from small to large that we can encode as ModeligToolkit `ODESystem`s (or other stuff). I want to assess the identifiability of these systems. However, I am unsure how to apply certain functions in the system to these (which seems primarily designed for StructuralIdentifiabiltiy ODEs).

Say that I have an identifiability problem, but know the value of certain initial conditions and parameters, how do I give StructuralIdentifiabiltiy this information? My only lead, the `set_parameter_values` function, seems to only work on ODEs defined by StructutralIdentifiability.

**Comment by pogudingleb** [comment]
Just to clarify: you would like to have a function which takes an `ODESystem` and sets some of the parameters to given constants? I can add it, I would just feel that it belongs rather to `ModelingToolkit`...

**Comment by TorkelE** [comment]
Sorry, yes, that would be a solution (however, I think this would be rather messy to do).

What I mean is, I want to assess the identifiability of a system. However, there are certain parameters and/or initial conditions that I know. E.g. if I have a system
```
dX/dt = - p1*p2 * X
```
I would get both `p1`, and `p2` unidentifiable (I presume). However, I want to supply the information that I know that value of `p1` (in which case identifiability for `p1` would never have to be assessed, and `p2` should become identifiable). 

How would I do this?

**Comment by pogudingleb** [comment]
Oh, I see.
If you want to indicate the knowledge but not a particular value, you can add this parameters as a measurable_quantity.
For initial conditions, unfortunately, for the moment we do not have this functionality.

**Comment by TorkelE** [comment]
Got it (For biology and chemistry this functionality would ver *very* useful).

I will see if I can coble together some internal hack to enable this for Catalyst (until the feature is added here, please ping me when you do).
