### ISSUE TITLE
Option for having a known initial condition

### ISSUE THREAD

**Issue by TorkelE** [SciML/StructuralIdentifiability.jl#237]
Currently, StructuralIdentifiability estimates the identifiability of all initial conditions and parameters. If a parameter is known, it is easy to incorporate this through
```julia
si_ode = @ODEmodel(
    X1'(t) = p - k1*X1(t),
    X2'(t) = X1(t) -  X2(t),
    y1(t) = X2(t),
    y2(t) = p
)
```
However, having certain initial conditions being known is very plausible (especially in cases where you set up the experiments yourself, such as in chemistry). 

If https://github.com/SciML/StructuralIdentifiability.jl/issues/236 gets solved (but I have no idea how hard that would be though), this would automatically become possible through:
```julia
si_ode = @ODEmodel(
    X1'(t) = p - k1*X1(t),
    X2'(t) = X1(t) -  X2(t),
    y1(t) = X2(t),
    y2(t) = X1(0)
)
```

**Comment by pogudingleb** [comment]
Yes, for generic known initial condition this should be doable, I should work on this at some point. Thanks!

**Comment by pogudingleb** [comment]
The functionality to add the known initial conditions (assuming that they are generic) has been added in release `0.5.4` (right now, for `@ODEmodel` macro only). An example is given in [this tutorial](https://docs.sciml.ai/StructuralIdentifiability/stable/tutorials/identifiability/)

**Comment by TorkelE** [comment]
That's exciting to learn! Thanks :)
