### ISSUE TITLE
Alternative names for certain kwargs?

### ISSUE THREAD

**Issue by TorkelE** [SciML/StructuralIdentifiability.jl#256]
The Catlayst/SI extension (https://github.com/SciML/Catalyst.jl/pull/709) should be merged soon (just waiting for an issue that popped up in Symbolcis that causes Catlayst tests to fail generally).

One thing that came up there was if there could be better names for some `kwargs`. E.g. the `p` kwarg for guaranteed minimum probability of correctness. Throughout SciML, `p` generally means parameters. In the end, we decided to use `prob_threshold` in the extension (which is then passed as `p` to SI.jl internally). Changing it in SI might be something to consider?

Another one that came up was whether `quantities_to_identify` or `quants_to_ident`, or maybe  `quants_to_check` would be better than `funcs_to_check`. This one, however, is kept as `funcs_to_check` in Catalyst for now.

**Comment by pogudingleb** [comment]
I completely agree about `p`, the letter is very overloaded. Also, this parameter is not normally changed by a user. I will rename it next week.

For `funcs_to_check`, the change would be more noticeable (this keyword is often used) while the advantages of `quants_to_check` (which I do not deny! ) over the current name do not seem to be significant for such a change. Maybe this would wait for a larger interface revision.
