### ISSUE TITLE
Using ModelingToolkit to mark ODE inputs and outputs for StructuralIdentifiability

### ISSUE THREAD

**Issue by Ickaser** [SciML/StructuralIdentifiability.jl#268]
**Describe the example**

The SciML tutorial for StructuralIdentifiability seems to indicate that we can mark variables as inputs or outputs, so that they should behave as knowns when identifiying unknown parameters, as in https://docs.sciml.ai/ModelingToolkit/dev/tutorials/parameter_identifiability/ . 

**Minimal Reproducible Example 👇**

Taken directly from the mentioned tutorial:
```julia
using StructuralIdentifiability, ModelingToolkit
@variables t
D = Differential(t)

@mtkmodel GoodwinOscillator begin
    @parameters begin
        b
        c
        α
        β
        γ
        δ
        σ
    end
    @variables begin
        x1(t)
        x2(t)
        x3(t)
        x4(t)
        y(t), [output = true]
        y2(t), [output = true]
        u1(t), [input = true]
        u2(t), [input = true]
    end
    @equations begin
        D(x1) ~ -b * x1 + 1 / (c + x4)
        D(x2) ~ α * x1 - β * x2 - u1
        D(x3) ~ γ * x2 - δ * x3 + u2
        D(x4) ~ σ * x4 * (γ * x2 - δ * x3) / x3
        y ~ x1 + x2
        y2 ~ x2
    end
end

@named ode = GoodwinOscillator()
ode = complete(ode)

# check only 2 parameters
to_check = [ode.b, ode.c]

global_id = assess_identifiability(ode, funcs_to_check = to_check, p = 0.9)
```

**Error & Stacktrace ⚠️**

```julia
[ Info: Measured quantities are not provided, trying to find the outputs in input ODE.
```
[followed by other info statements about calculation progress]

```julia
OrderedCollections.OrderedDict{Num, Symbol} with 2 entries:
  b => :globally
  c => :globally
```
So, the result from the tutorial is as described, but relies on this automatic detection of the ODE outputs. In the somewhat-more-complicated example I am interested in, **SI seems unable to infer from my ODE specification what the outputs are**, although I have tried to closely follow the tutorial syntax, including marking variables with `[input = true]` or `[output = true]`.

A closely related but possibly separate question:
Given the above, I would like to better understand the syntax requirements for marking variables as "measured". In my model of interest, I have several knowns or parameters calibrated by different techniques; should I somehow mark these as known?
In the tutorials and docs I have found, the keyword argument is constructed with
```julia
measured = [de.y ~ de.x1 + de.x2, de.y2 ~ de.x2]
assess_identifiability(de, measured_quantities = measured)
```
It feels clunky to me to introduce new auxiliary variables with `y ~ x1+x1` and `y2~x2` to mark as measured, instead of just listing `x1+x2` and `x2` as measured, and I am unclear how this should work for e.g. known, controllable system inputs, of which I have several. **Do I just need to introduce a bunch of new auxiliary variables so I can mark them all as measured?**

**Not Working Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
⌃ [336ed68f] CSV v0.10.11
⌃ [0c46a032] DifferentialEquations v7.8.0
⌃ [e30172f5] Documenter v0.27.24
⌃ [634d3b9d] DrWatson v2.12.5
⌃ [961ee093] ModelingToolkit v8.70.0
  [16a59e39] ModelingToolkitStandardLibrary v2.3.4
⌃ [7f7a1694] Optimization v3.15.2
⌃ [500b13db] OptimizationPolyalgorithms v0.1.1
⌃ [91a5bcdd] Plots v1.38.16
  [aea7be01] PrecompileTools v1.2.0
  [189a3867] Reexport v1.2.2
⌃ [f2b01f46] Roots v2.0.20
⌃ [1ed8b502] SciMLSensitivity v7.33.1
  [220ca800] StructuralIdentifiability v0.5.1
⌃ [1986cc42] Unitful v1.14.0
⌃ [e88e6eb3] Zygote v0.6.62
```

  - Output of `versioninfo()`

```julia
Julia Version 1.10.0
Commit 3120989f39 (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores

```

**Comment by pogudingleb** [comment]
@Ickaser , thank you for a detailed report!

The tutorial was written some time ago (although still works fine), so it would be great to update it, I have created an [issue](#269 ). In fact, the standard expected way to mark the measured quantities is via `measure_quantities`, this is why the situation when they are marked by `[output=true]` invokes and extra `@info` statement. However, the mechanism via `[output=true]` should work, and it works on the example you give. If you have an example in which it does not work, could you provide it?

> In my model of interest, I have several knowns or parameters calibrated by different techniques; should I somehow mark these as known?

Yes, you can add them to `measured_quantities`.

> It feels clunky to me to introduce new auxiliary variables with y ~ x1+x1 and y2~x2 to mark as measured, instead of just listing x1+x2 and x2 as measured

We also realised this at some point, so now it is possible to provide `measured_quantities` as just a list of expressions, so in your example it will be

```julia
assess_identifiability(ode, measured_quantities = [ode.x1 + ode.x2, ode.x2])
```

I hope this looks more convenient for you.
 
> known, controllable system inputs, of which I have several

If you have inputs in your model (so they do not appear on the left-hand side), they will be assumed known by default, there is no need to explicitly mark them as such.

Let me know if you have any further questions/feedback.
