### ISSUE TITLE
`mtk_to_si` no longer defined/exported with new functionality.

### ISSUE THREAD

**Issue by TorkelE** [SciML/StructuralIdentifiability.jl#279]
Simple MWE:
```julia
using StructuralIdentifiability
mtk_to_si # ERROR: UndefVarError: `mtk_to_si` not defined
using ModelingToolkit
mtk_to_si # ERROR: UndefVarError: `mtk_to_si` not defined
```
I think this was caused by the latest update.

Currently, this is breaking tests in Catalyst, hence I discovered it: https://github.com/SciML/Catalyst.jl/actions/runs/7743939220/job/21116510775?pr=776

I checked the source code. I am not really sure, but when I make extensions I do not put export statements in the extension file. Instead, I create a `mtk_to_si` function (without methods) in the main file, and then add methods to that in the extension. E.g. in Catalyst's HomotopyContinuation extension I have this in Catalyst.jl
```julia
# HomotopyContinuation
function hc_steady_states end
export hc_steady_states
```
and this in homotopy_continuation_extension.jl
```julia
function Catalyst.hc_steady_states(rs::ReactionSystem, ps; filter_negative=true, neg_thres=-1e-20, u0=[], kwargs...)
    ss_poly = steady_state_polynomial(rs, ps, u0)
    sols = HC.real_solutions(HC.solve(ss_poly; kwargs...))
    reorder_sols!(sols, ss_poly, rs)
    return (filter_negative ? filter_negative_f(sols; neg_thres) : sols)
end
```
This might be worth a try.

**Comment by TorkelE** [comment]
I actually just finished a PR for it, see: https://github.com/SciML/StructuralIdentifiability.jl/pull/280
(but feel welcome to just do your own solution)

I encountered another problem there which might need checking as well.

Yes, I struggled quite a bit when I wrote the extensions. They work, but it is not super intuitive, and there are no good descriptions of how to do it.

**Comment by TorkelE** [comment]
If you haven't already, could you tag a new release so that Catalyst could use it for the tests?

**Comment by pogudingleb** [comment]
Sure, this is not version `0.5.3`

**Comment by TorkelE** [comment]
Thanks :)
