### ISSUE TITLE
Issue assessing identifiability for enzyme hydrolysis models

### ISSUE THREAD

**Issue by MarcusGalea** [SciML/StructuralIdentifiability.jl#363]
I'm trying to assess the identifiability of reaction rates in a typical enzyme reaction model with hydrolysis. The measured quantity is an accumulated weight of several species over time. Unfortunately, `assess_identifiability` gets stuck while computing IO-equations for this model. Is this a local issue, or is there something intrinsically difficult about solving this problem? This is my code: 
```julia

using Catalyst
using StructuralIdentifiability

#creating a model
@parameters t #time
vars = @variables E(t) S(t) ES(t) P(t) #species
@parameters k_a k_d k_c


#underlying model describing the data
# binding and unbinding of enzyme and substrate:
model = @reaction_network begin
    @parameters wE wS wP
    k_a, E + S --> ES
    k_d, ES --> S + E
    k_c, ES --> P + E
end



#known initial conditions
known_ic = [E, S, ES, P]


#the measured quantities are the sum of the weights of the species
@unpack wE, wS, wP = model
measured_quantities = [(wE+wS)*ES + wP*P + wS*S]

#convert the model to an ODE system
ODE = convert(ODESystem, model)
StructuralIdentifiability.assess_identifiability(ODE, measured_quantities = measured_quantities; funcs_to_check = [k_a, k_d, k_c])
```
Thanks in advance!

**Comment by pogudingleb** [comment]
@MarcusGalea 
Thanks for the interesting example! Indeed, the model is small but due to its nonlinearity direct identifiability computation gets stuck. A possible workaround is to use a conservation law `E + ES = C` in order to eliminate `E`. The resulting model is equivalent to the original one but much easier for the computation. Here is the code
```julia
ode = @ODEmodel(
       S'(t) = k_d * ES(t) - k_a * S(t) * (C - S(t)),
       ES'(t) = -k_c * ES(t) - k_d * ES(t) + k_a * (C - S(t)) * S(t),
       P'(t) = k_c * ES(t),
       y(t) = (wE + wS) * ES(t) + wP * P(t) + wS * S(t)
)
assess_identifiability(ode, known_ic = [S, ES, P, C - S])
```
We want to have this conversion to be done automatically but not yet there.

**Comment by MarcusGalea** [comment]
Thanks for the quick response! Apparently they are trying to address this issue in catalyst by running `Catalyst.conservedequations` before assessing identifiability directly on Catalyst reaction models. This is a change added for [Catalyst 14.0](https://github.com/SciML/Catalyst.jl/blob/master/HISTORY.md). It doesn't seem to be working right now, due to changes in upstream packages. I guess I'll be waiting for this to be fixed in the future, when I'll be working with more complicated reaction networks.
