### ISSUE TITLE
UTF (e.g., Greek letters) are not supported

### ISSUE THREAD

**Issue by pogudingleb** [SciML/StructuralIdentifiability.jl#43]
Greek letters yield an error, MWE:
```juia
using StructuralIdentifiability

ode = @ODEmodel(
    x'(t) = α * x(t),
    y(t) = x(t)
)
assess_identifiability(ode)
```
This is because they are not supported by `Singular`. Conversion to `Singular` is currently used in two places
* factorization, to be eliminated by [this issue](https://github.com/SciML/StructuralIdentifiability.jl/issues/42)
* GB computation at the end

**Comment by iliailmer** [comment]
It seems that https://sumiya11.github.io/Groebner.jl/ can support the Unicode variable names. Could also be relevant to #55 .

**Comment by pogudingleb** [comment]
Yes, this is true. I believe that Sasha first wanted to finish some things in the package before it can be used in `StructuralIdentifiability`, I will keep in touch with him about this

**Comment by iliailmer** [comment]
@pogudingleb Thank you!

**Comment by pogudingleb** [comment]
Starting with version 0.4.0 greek letters are supported

**Comment by finmod** [comment]
This issue is solved. Greek letters are fine in this tutorial. Update the docs accordingly.
