### ISSUE TITLE
Precompile error

### ISSUE THREAD

**Issue by vembha** [SciML/StructuralIdentifiability.jl#82]
Unable to load `StructuralIdentifiability.jl` after installation without errors. Tried multiple clean installations, but the error persists. Following is the StackTrace error and version numbers:

`
[220ca800] StructuralIdentifiability v0.3.6
`
`
[961ee093] ModelingToolkit v8.4.1
`

[ Info: Precompiling StructuralIdentifiability [220ca800-aa68-49bb-acd8-6037fa93a544]
ERROR: LoadError: UndefVarError: libsingular not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:26
 [2] top-level scope
   @ C:\Users\Bharadwaj\.julia\packages\Singular\nGiup\src\Singular.jl:66
 [3] include
   @ .\Base.jl:386 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base .\loading.jl:1235
 [5] top-level scope
   @ none:1
 [6] eval
   @ .\boot.jl:360 [inlined]
 [7] eval(x::Expr)
   @ Base.MainInclude .\client.jl:446
 [8] top-level scope
   @ none:1
in expression starting at C:\Users\Bharadwaj\.julia\packages\Singular\nGiup\src\Singular.jl:1
ERROR: LoadError: Failed to precompile Singular [bcd08a7b-43d2-5ff7-b6d4-c458787f915c] to C:\Users\Bharadwaj\.julia\compiled\v1.6\Singular\jl_9131.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
    @ Base .\loading.jl:1385
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1329
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1043
  [5] require(uuidkey::Base.PkgId)
    @ Base .\loading.jl:936
  [6] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:923
  [7] include
    @ .\Base.jl:386 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1235
  [9] top-level scope
    @ none:1
 [10] eval
    @ .\boot.jl:360 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude .\client.jl:446
 [12] top-level scope
    @ none:1
in expression starting at C:\Users\Bharadwaj\.julia\packages\GroebnerBasis\89ud7\src\GroebnerBasis.jl:1
ERROR: LoadError: Failed to precompile GroebnerBasis [e39c9192-ea4d-5e15-9584-a488c6d614bd] to C:\Users\Bharadwaj\.julia\compiled\v1.6\GroebnerBasis\jl_8BC2.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
    @ Base .\loading.jl:1385
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1329
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1043
  [5] require(uuidkey::Base.PkgId)
    @ Base .\loading.jl:936
  [6] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:923
  [7] include
    @ .\Base.jl:386 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base .\loading.jl:1235
  [9] top-level scope
    @ none:1
 [10] eval
    @ .\boot.jl:360 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude .\client.jl:446
 [12] top-level scope
    @ none:1
in expression starting at C:\Users\Bharadwaj\.julia\packages\StructuralIdentifiability\0qdZi\src\StructuralIdentifiability.jl:1
ERROR: Failed to precompile StructuralIdentifiability [220ca800-aa68-49bb-acd8-6037fa93a544] to C:\Users\Bharadwaj\.julia\compiled\v1.6\StructuralIdentifiability\jl_84FE.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
   @ Base .\loading.jl:1385
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1329
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1043
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:936
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:923

**Comment by pogudingleb** [comment]
@vembha Thank you for reporting! What is your operating system? Windows?

**Comment by vembha** [comment]
@pogudingleb Yeah, it is Windows. Also, I'm unable to add `SIAN.jl` package, but that also did had precompilation issue. Nevertheless, `ModelingToolkit.jl` was fine.

**Comment by vembha** [comment]
> I see. Yes, this is known problem (#70 ). We are working on this, and will let you know once this is fixed. Meanwhile, you can install the package in Linux or Mac. You can also send a model to check to me, I can do this for you.

Thank you @pogudingleb. Glad that the error is not at my end. 😅 I have a Linux machine and I shall try on it. 👍

**Comment by qchenmath** [comment]
> > I see. Yes, this is known problem (#70 ). We are working on this, and will let you know once this is fixed. Meanwhile, you can install the package in Linux or Mac. You can also send a model to check to me, I can do this for you.
> 
> Thank you @pogudingleb. Glad that the error is not at my end. 😅 I have a Linux machine and I shall try on it. 👍

Was you able to add the package on your Linux machine? I failed...

**Comment by vembha** [comment]
> > > I see. Yes, this is known problem (#70 ). We are working on this, and will let you know once this is fixed. Meanwhile, you can install the package in Linux or Mac. You can also send a model to check to me, I can do this for you.
> > 
> > 
> > Thank you @pogudingleb. Glad that the error is not at my end. 😅 I have a Linux machine and I shall try on it. 👍
> 
> Was you able to add the package on your Linux machine? I failed...

@qchenmath Yeah. I last checked it around two weeks ago and the package is working fine on a Linux machine.

**Comment by qchenmath** [comment]
> > > > I see. Yes, this is known problem (#70 ). We are working on this, and will let you know once this is fixed. Meanwhile, you can install the package in Linux or Mac. You can also send a model to check to me, I can do this for you.
> > > 
> > > 
> > > Thank you @pogudingleb. Glad that the error is not at my end. 😅 I have a Linux machine and I shall try on it. 👍
> > 
> > 
> > Was you able to add the package on your Linux machine? I failed...
> 
> @qchenmath Yeah. I last checked it around two weeks ago and the package is working fine on a Linux machine.

That is good to know. I failed to add 5 packages. The details are posted here:

https://github.com/SciML/StructuralIdentifiability.jl/issues/70

**Comment by qchenmath** [comment]
Post my error messages on another thread by accident. Anyways, so far I tried to add the package on Windows 10, Linux (centos), and MacPro (M1), without success. The linux and MacPro (M1) can't precompile for 6 packages - not all 6 are the same though.

**Comment by iliailmer** [comment]
@qchenmath Windows system unfortunately is not supported by `Singular.jl`. It should work on M1 with Julia-1.6 (via Rosetta). Native version (Julia-1.7 and higher) fails due to `BinaryProvider.jl` not working on M1 processors.

Were you installing using Julia-1.6 or 1.7 on the M1?

**Comment by qchenmath** [comment]
> @qchenmath Windows system unfortunately is not supported by `Singular.jl`. It should work on M1 with Julia-1.6 (via Rosetta). Native version (Julia-1.7 and higher) fails due to `BinaryProvider.jl` not working on M1 processors.
> 
> Were you installing using Julia-1.6 or 1.7 on the M1?

Saw it somewhere else. Just changed to Julia 1.7.2 (via Rosetta). Working fine now.

**Comment by pogudingleb** [comment]
@vembha 
The new release 0.4.0 works on Windows, please let us know if you encounter any issues if you decide to try on a Windows machine.

**Comment by vembha** [comment]
@pogudingleb Yes, it is now working! Thank you. :)
