### ISSUE TITLE
Generic functions in equations?

### ISSUE THREAD

**Issue by baggepinnen** [SciML/StructuralIdentifiability.jl#94]
I had a go at defining a system with state `h`, inputs `u` and outputs `y`, 
```julia
using StructuralIdentifiability

ode = @ODEmodel(
    h1'(t) = -a/A * sqrt(18*h1(t)) + a/A*sqrt(18*h3(t)) +     γ*k/A * u1(t),
    h2'(t) = -a/A * sqrt(18*h2(t)) + a/A*sqrt(18*h4(t)) +     γ*k/A * u2(t),
    h3'(t) = -a/A*sqrt(18*h3(t))                          + (1-γ)*k/A * u2(t),
    h4'(t) = -a/A*sqrt(18*h4(t))                          + (1-γ)*k/A * u1(t),
	y1(t) = h1(t),
    y2(t) = h2(t),
)

local_id = assess_local_identifiability(ode, 0.99)
```
it looks like parameters, states, inputs and outputs were correctly identified, except it thinks that `sqrt` is a parameter, and as a consequence it fails:
```
[ Info: Summary of the model:
[ Info: State variables: h1, h2, h3, h4
[ Info: Parameters: A, k, a, γ, sqrt
[ Info: Inputs: u1, u2
[ Info: Outputs: y1, y2
ERROR: Number of variables does not match number of values
```
If I remove `sqrt`, it accepts the definition. I couldn't figure out from the docs whether or not this is a known limitation or a bug?

**Comment by pogudingleb** [comment]
@baggepinnen 
Currently, the package solves only systems with rational (that is, polynomial divided by polynomial) right-hand side, square roots are not allowed.
One workaround could be to write a system of equations on `sqrt(h1), .., sqrt(h4)`, not on `h1, ..., h4` themselves.

**Comment by baggepinnen** [comment]
Thanks for your input @pogudingleb, the suggested workaround is indeed perfectly fine for this system :)
